### PR TITLE
makefile tweaks to execute tests on my machine

### PR DESCRIPTION
**Pull request by rchikhi**

### CODE REVIEW

**Comment by richarddurbin** [comment]
Hello Rayan

I am fine with adding ONElogan so long as it is in SEQUENCE_UTILITIES/, not the top level ONEcode directory.  Also I'd like you to add some comment at the top of it to say that you wrote it, with me if you want.  I can't work out from the github interface where it will be added.

I am also fine with changing the Makefile to wrap the test in an explicit shell call.  But I don't understand the changes to t1.sh and t2.sh, which seem to make them empty.  Was that the intention, or is it a mistake, or am I misinterpreting the github interface?

All the best

Richard

**Review by richarddurbin — APPROVED** [review]
OK.  Now I see that the changes to TEST/t[12].sh are just changing from Unix mode 644 to 755, i.e. making them executable.  Fine.  I am happy with that.

**Comment by rchikhi** [comment]
hi Richard! oops, ONElogan wasn't supposed to be part of this pull request :)  I'll take it out

**Comment by rchikhi** [comment]
oh it got merged just now! OK then, will do the suggested changes

**Comment by richarddurbin** [comment]
I am OK with it being there if you are.
Why don’t you add a link to the home page for the logan project and an example in the usage?

Richard

From: Rayan Chikhi ***@***.***>
Date: Wednesday, 21 August 2024 at 15:10
To: thegenemyers/ONEcode ***@***.***>
Cc: Richard Durbin ***@***.***>, State change ***@***.***>
Subject: Re: [thegenemyers/ONEcode] makefile tweaks to execute tests on my machine (PR #2)

oh it got merged just now! OK then, will do the suggested changes

**Comment by rchikhi** [comment]
I did in this new PR :) https://github.com/thegenemyers/ONEcode/pull/3/files

**Comment by richarddurbin** [comment]
Thanks.  I merged that.

From: Rayan Chikhi ***@***.***>
Date: Wednesday, 21 August 2024 at 16:59
To: thegenemyers/ONEcode ***@***.***>
Cc: Richard Durbin ***@***.***>, State change ***@***.***>
Subject: Re: [thegenemyers/ONEcode] makefile tweaks to execute tests on my machine (PR #2)

I did in this new PR :) https://github.com/thegenemyers/ONEcode/pull/3/files

**Pull request merged**
